import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import * as React from 'react';
// import Button from '@mui/material/Button';

import {
    FormControl,
    FormLabel,
    FormErrorMessage,
    FormHelperText, Button, Input, Box
} from '@chakra-ui/react'

// import { Button, ButtonGroup } from '@chakra-ui/react'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {/* <div className={styles.description}> */}
                {/* <Button variant="contained">Hello World</Button> */}
                {/* </div> */}
                <Box m={2} borderColor='gray.200'>
                    <FormControl>
                        <FormLabel>Email address</FormLabel>
                        <Input type='email' />
                        <FormHelperText>We'll never share your email.</FormHelperText>

                        <Box p={2}>  <Button colorScheme='blue'>Button</Button></Box>
                    </FormControl>
                </Box>

            </main>
        </>
    )
}
