import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Field, Form, Formik } from 'formik';
const inter = Inter({ subsets: ['latin'] })
import {
  FormControl,
  Input,
  FormLabel, Box,
  FormErrorMessage,
  FormHelperText, Badge, Stack, Center, Button, Alert, VStack, Textarea, Text,useToast
  // AlertIcon,
  // AlertTitle,
  // AlertDescription,
} from '@chakra-ui/react'

import FormData from '../components/form' // import from component example : form
import AlertComponent from '../components/alert'
import Router from 'next/router';
import { useState } from "react";

export default function Home() {

  const [value, changeValue] = useState(""); // set state for handle data from form field
  const toast = useToast(); // use toast, please install chakra ui toast first

  function hanldeData(params) {

    console.log(value);

  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FormData inputValue={value} onInputValueChange={changeValue}></FormData> // call component from compoent folder
      <Box m={10} > <AlertComponent data="fahsdfsdfsmi"></AlertComponent></Box>

      <VStack alignItems="start" m={3} >
        <Text mb='8px'>Masukkan Deskripsi kendala pada Talis 30MJ {value}</Text>
        <Textarea></Textarea>
      </VStack>


      <Button colorScheme='blue' onClick={() => Router.push('/frame-record')}>Button</Button>
      <Button colorScheme='blue' onClick={() => 

      // this for call the toast
      toast({
        title: 'Account created.',
        description: `We've created your account for you. ${value}`,
        status: 'success',
        duration: 9000,
        isClosable: true,
    })}>toast</Button>


      {/* <Center>
        <Box m={10}>
          <Stack direction='row'>
            <Box >   <FormControl >
              <FormLabel>Masukkan Nama </FormLabel>
              <Input placeholder='Nama Anda' borderRadius="16px"/>
            </FormControl></Box>
            <Box>  <FormControl isRequired>
              <FormLabel>First name</FormLabel>
              <Input placeholder='First name' />
            </FormControl></Box>
          </Stack>
        </Box>
      </Center> */}




      {/* <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </>
  )
}
